language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - nightly

before_script:
  - composer install
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com

script:
  - ./bin/phpchunkit --exclude-group=functional --parallel=2 --num-chunks=4 --verbose --debug
  - ./bin/phpchunkit --group=functional --sandbox --create-dbs --parallel=2 --num-chunks=4 --verbose --debug

git:
  depth: 1

notifications:
  irc:
    channels:
      - "irc.freenode.net#phpchunkit"
    on_success: change

