language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 7.1
  - nightly

before_script:
  - composer install
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com
  - mysql -e "create database IF NOT EXISTS testdb1_test;" -uroot
  - mysql -e "create database IF NOT EXISTS testdb2_test;" -uroot

script:
  - ./vendor/bin/phpunit

git:
  depth: 1

notifications:
  irc:
    - "irc.freenode.net#phpchunkit"

